##################################################################################################
## yaml 문법
## 하위 계층으로 내려갈 때 tab이 아닌 스페이스바를 사용하고, 콜론(:)이나 하이픈(-) 이후에 공백 한칸도 필요하다!!
##################################################################################################

#Enc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: "${SCHEDULE_ENCRYPT:}"
    property:
      prefix: ENC(
      suffix: )

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schdb
    username: ENC(EtkDutNBQdiXl6emQ8DWog==)
    password: ENC(/g5RmeebB1keSoZe38Mu62Lvu1GWJ8d4)
    dbName: ENC(asCNfBuIkMzKmWqpRUHZ8g==)
    maxTotal: 100
    maxIdle: 10
    minIdle: 1
    maxWaitMillis: 1000
    configLocation: classpath:META-INF/mybatis/mybatis-config.xml
    mapperLocations: classpath*:com/schedule/SQL/**/*.xml
    maxOpenPreparedStatements: 100
    testOnBorrow: true
    testWileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000

logging:
  level:
    root: DEBUG
    sun: DEBUG
    org:
      openqa.selenium: WARN
      apache: WARN
      quartz: WARN
      springframework: WARN
      springframework.web: WARN
      hibernate: ERROR
    # showSql
    jdbc: WARN
    jdbc.sqlonly: WARN
    # log SQL with timing information, post execution
    jdbc.sqltiming: INFO
    # log4jdbc option  log the jdbc results as a table
    jdbc.resultsettable: INFO

    javax: INFO

    springfox: WARN

    org.mybatis: INFO
    java:
      sql: INFO
      sql.connection: DEBUG
      sql.Statement: DEBUG
      sql.PreparedStatement: DEBUG
    com.refine:
      SQL: WARN
      common.RfContextAware: DEBUG
    biz.refine: WARN
    log4jdbc.debug : WARN