##################################################################################################
## yaml 문법
## 하위 계층으로 내려갈 때 tab이 아닌 스페이스바를 사용하고, 콜론(:)이나 하이픈(-) 이후에 공백 한칸도 필요하다!!
##################################################################################################

#Enc
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: "${SCHEDULE_ENCRYPT:}"
    property:
      prefix: ENC(
      suffix: )

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schdb
    username: ENC(EtkDutNBQdiXl6emQ8DWog==)
    password: ENC(/g5RmeebB1keSoZe38Mu62Lvu1GWJ8d4)
    dbName: ENC(asCNfBuIkMzKmWqpRUHZ8g==)
    maxTotal: 100
    maxIdle: 10
    minIdle: 1
    maxWaitMillis: 1000
    configLocation: classpath:META-INF/mybatis/mybatis-config.xml
    mapperLocations: classpath*:com/schedule/SQL/**/*.xml
    maxOpenPreparedStatements: 100
    testOnBorrow: true
    testWileIdle: true
    validationQuery: SELECT 1
    validationInterval: 30000